### Import the relevant libraries

In [2]:
import numpy as np

## Addition

In [3]:
# The two matrices must have the same dimensions

In [4]:
matrix_1 = np.array([[1,3,-6], [8,2,17]])
matrix_1

array([[ 1,  3, -6],
       [ 8,  2, 17]])

In [6]:
matrix_2 = np.array([[5,2,9] , [6,7,1]])
matrix_2

array([[5, 2, 9],
       [6, 7, 1]])

In [7]:
matrix_1 + matrix_2

array([[ 6,  5,  3],
       [14,  9, 18]])

## Subtraction

In [8]:
# The two matrices must have the same dimensions

In [9]:
matrix_3 = np.array([[5,3] , [7,2]])
matrix_3

array([[5, 3],
       [7, 2]])

In [10]:
matrix_4 = np.array([[1,1] , [10,0]])
matrix_4

array([[ 1,  1],
       [10,  0]])

In [11]:
matrix_3 - matrix_4

array([[ 4,  2],
       [-3,  2]])

## Adding vectors together

In [17]:
# the length of the two vectors must be the same

In [14]:
vector_1 = np.array([4,8,4,1])
vector_1

array([4, 8, 4, 1])

In [15]:
vector_2 = np.array([1,6,3,8])
vector_2

array([1, 6, 3, 8])

In [16]:
vector_1 + vector_2

array([ 5, 14,  7,  9])

## Substraction of vectors

In [19]:
vector_1 - vector_2

array([ 3,  2,  1, -7])