## Import the relevant libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
# The simplest most flexible way to work with matrices in Python
# is by using arrays

### Scalars

In [29]:
scalar_ = 6
scalar_

6

### Vectors

In [30]:
vector_ = np.array([8,2,10])
vector_

# vector_ is a row vector

array([ 8,  2, 10])

### Matrices

In [31]:
matrix_ = np.array([[12, 6, -3] , [-1, 5, 0]])
matrix_

array([[12,  6, -3],
       [-1,  5,  0]])

### Data types

In [32]:
type(scalar_)

int

In [33]:
type(vector_)

numpy.ndarray

In [34]:
type(matrix_)

numpy.ndarray

In [35]:
# ndarray = n-dimensional array
# vector_ = 1-dimensional array
# matrice_ = 2-dimensional array

In [36]:
scalar_2 = np.array(5)
scalar_2

array(5)

In [37]:
type(scalar_2)

numpy.ndarray

### Data shapes

In [38]:
matrix_.shape

(2, 3)

In [39]:
vector_.shape

(3,)

In [40]:
# reshape gives an array a new shape, without changing its data

vector_.reshape(1,3)

array([[ 8,  2, 10]])

In [41]:
vector_.reshape(3,1)

array([[ 8],
       [ 2],
       [10]])

In [42]:
scalar_2.shape

()