### Import the relevant libraries

In [1]:
import numpy as np

### Creating a tensor

In [4]:
matrix_1 = np.array([[6,3,16] , [9,-4,0]])
matrix_1

array([[ 6,  3, 16],
       [ 9, -4,  0]])

In [5]:
matrix_2 = np.array([[5,12,-6] , [24, 8, 2]])
matrix_2

array([[ 5, 12, -6],
       [24,  8,  2]])

In [6]:
tensor_1 = np.array([matrix_1, matrix_2])
tensor_1

array([[[ 6,  3, 16],
        [ 9, -4,  0]],

       [[ 5, 12, -6],
        [24,  8,  2]]])

### Checking its shape

In [7]:
tensor_1.shape

(2, 2, 3)

### Manually creating a tensor

In [10]:
tensor_manual = np.array([[[6,3,16] , [9,-4,0]],[[5,12,-6] , [24, 8, 2]]])
tensor_manual

array([[[ 6,  3, 16],
        [ 9, -4,  0]],

       [[ 5, 12, -6],
        [24,  8,  2]]])